### ISSUE TITLE
[BUG]  [UI]  包无忧店铺登陆 BUG－0009 店铺信息设置界面的店铺代码输入框无光标显示

### ISSUE THREAD

**Issue by 1182311224** [smileyWay/bwy#10]
1、进入包无忧软件中的设置－店铺信息设置界面；
2、此时店铺代码输入框无光标显示；
3、手动点击代码输入框，仍无光标显示，但输入框可以输入信息；
4、期望结果：在刚进入店铺信息设置界面时，店铺代码输入框可以自动获取光标；

**Comment by smileyWay** [comment]
bug原因：输入框文字对齐方式错误。
修改方法：设置输入框文字对齐方式为居中。
备注：请验证是否修复。

**Comment by 1182311224** [comment]
bug已修复，测试通过。
