### ISSUE TITLE
[BUG]  [UI]  包无忧店铺登陆 BUG－0010 莲花新区店铺的到件信息内容缺失

### ISSUE THREAD

**Issue by 1182311224** [smileyWay/bwy#11]
1、a手机号通过其自身的微信号成功绑定到包无忧；
2、进入包无忧软件中的店铺信息设置界面进行店铺选择，输入莲花新区店铺代码：000003，保存后成功进入莲花新区店铺系统；
3、进行快递员的上传、入库以及代收点的短信通知用户到件，测试运单号：2578 6591，测试的a手机号为：15281099163；
4、a手机号的微信和短信获得的到件信息内容中，地址错误的为：锦江区号莲花新区3栋1层包无忧自提点；
5、期望结果：莲花中路48号莲花新区3栋1单元1层包无忧自提点；

**Comment by smileyWay** [comment]
<img width="718" alt="079af229-1159-46cb-bb6b-0bf69ee99f28" src="https://cloud.githubusercontent.com/assets/13463738/17241088/fcab1446-55a1-11e6-9880-6c288b238043.png">
由于张辉提供的资料错误导致，已经更改。

**Comment by 1182311224** [comment]
bug已修复，测试通过
