### ISSUE TITLE
[BUG]  [UI]  包无忧店铺登陆 BUG－0011 当输入错误店铺代码时出现的提示在输入正确的店铺代码后，提示仍然显示

### ISSUE THREAD

**Issue by 1182311224** [smileyWay/bwy#12]
1、进入包无忧软件－设置－店铺信息设置界面；
2、输入任意错误的店铺代码：0001；
3、点击确定按钮后，屏幕上会显示：“认证代码错误“的提示；
4、此时输入正确的店铺代码：000001，再点击确定按钮后，”认证代码错误“的提示仍然存在；
5、期望结果：当输入错误店铺代码时出现的提示在输入正确的店铺代码后消失；

**Comment by smileyWay** [comment]
bug原因：正确获取店铺信息后，没有刷新显示信息。
修改方法：在获取店铺信息后，再次刷新UI显示的信息。
备注：请验证是否修改。

**Comment by 1182311224** [comment]
bug已修复，测试通过
