### ISSUE TITLE
【崩溃】BUG-0002 Wifi 网络下挂接HTTP代理服务器会导致发送短信时 App 崩溃的问题

### ISSUE THREAD

**Issue by Malthanl** [smileyWay/bwy#3]
1. 在 iOS 设置中为 当前Wifi 连接设置 HTTP 代理服务器，如下图所示

![img_0036](https://cloud.githubusercontent.com/assets/4828339/14340008/b0bad55c-fcb5-11e5-878d-bbb9dcf9953e.jpg)
1. 在此网络环境下尝试为包裹发送取件密码短信
2. 发现此情况下存在较高几率导致 App 崩溃。崩溃日志文件如下

[CrashLog.crash.zip](https://github.com/smileyWay/bwy/files/206644/CrashLog.crash.zip)

备注：
1. 在此情况下首次发送短信 App 会提示短信发送成功
2. 实际在短信后台查不到任何已发送短信的信息 
3. 如果继续尝试发送短信，就会有较大几率导致 App 崩溃

**Comment by smileyWay** [comment]
能否提供：“ Wifi 连接设置 HTTP 代理服务器” 的配置信息或截图？

**Comment by Malthanl** [comment]
靠，忘记裁图了，那么大

**Comment by Malthanl** [comment]
好了，截图已附加

**Comment by Malthanl** [comment]
1. 在此情况下首次发送短信 App 会提示短信发送成功
2. 实际在短信后台查不到任何已发送短信的信息
   3.如果继续尝试发送短信，就会有较大几率导致 App 崩溃
