### ISSUE TITLE
【问题】BUG-0004 已出库包裹再次上货架但不能再出库的问题

### ISSUE THREAD

**Issue by Malthanl** [smileyWay/bwy#5]
1. 正常登记并上架某包裹条码，比如条码尾号为1234。
2. 发送该包裹的取件短信，得到取件密码后输入该密码将此包裹出库。
3. 输入条码信息，再次将该包裹上架（模拟因拿错包裹而返还重新上架的情景）。
4. 重新发送该包裹的取件短信至新的手机号码
5. 发现新的手机号上收到的取件短信和之前的手机号收到的是一样的，如下图所示
   ![1](https://cloud.githubusercontent.com/assets/4828339/14662502/496cd5d8-06e9-11e6-9e0b-fa98e4a5348c.png)
6. 输入该取件密码后却发现“出库”按钮无法操作，无法进行出库操作

**Comment by smileyWay** [comment]
目前功能基本上是以非异常流程进行处理，异常流程的处理可以考虑提出需求进行添加。
