### ISSUE TITLE
【问题】BUG-0005 包裹出库后其对应的取件密码没有作废的问题

### ISSUE THREAD

**Issue by Malthanl** [smileyWay/bwy#6]
1. 正常按照登记，上架，发送取件短信的流程通知住户取件
2. 输入取件密码完成包裹出库操作
3. 发现可再次输入该取件密码进行包裹详情查询，也就是说该密码没有因出库而作废

**Comment by smileyWay** [comment]
密码因出库而作废,这个可以当做新需求来提出。需要考虑密码作废后如何查询包裹详情。
