### ISSUE TITLE
[BUG]  [功能]  包无忧店铺登陆 BUG－0006 包无忧微信公众号无法获取取件成功反馈信息 

### ISSUE THREAD

**Issue by 1182311224** [smileyWay/bwy#7]
1、a手机号通过其微信号成功绑定到包无忧；
2、进入包无忧软件中的设置－店铺信息设置界面进行店铺选择，输入店铺代码：000001，保存后成功进入钢五区系统；
3、在包无忧系统中进入快递员上传以及入库操作、代收点的短信通知用户到件，测试运单号：65654535，测试的a手机号为：15281099163；
4、a手机号的微信号成功获得到件信息通知，取件码：455589；
5、在客户－取件处输入取件码并成功取件，a手机号的微信号未获取到取件成功反馈的通知，而通过取件的接口测试，a手机的微信号可以获得取件成功的反馈通知；
6、期望结果：a手机的微信号可以正常获取取件成功的反馈通知；

**Comment by smileyWay** [comment]
bug原因：服务器端代码未读取店铺电话号码，导致调用微信接口时失败。
修改方法：修改服务器端代码，正确读取店铺代码。
备注：请验证bug是否修复。

**Comment by 1182311224** [comment]
BUG已修复，测试已通过。
