### ISSUE TITLE
[BUG]  [UI]  包无忧店铺登陆 BUG-0008 钢五区店铺的短信和微信到件信息内容有误以及内容过长

### ISSUE THREAD

**Issue by 1182311224** [smileyWay/bwy#9]
1、a手机号通过其自身的微信号成功绑定到包无忧；
2、进入包无忧软件中的设置－店铺信息设置界面进行店铺选择，输入钢五区店铺代码：000001，保存后并成功进入钢五区系统；
3、进行快递员的上传以及入库操作、代收点的短信通知用户到件，测试运单号：65654535，测试的a手机号为：15281099163；
4、a手机号的短信和微信获得的到件信息的温馨提示内容中，电话号码格式错误为：180-30452593；
5、并且钢五区的短信内容过长；
6、期望结果：获得到件信息的温馨提示内容中，电话号码的格式为：18030452593，并且内容是否可以简短；

**Comment by smileyWay** [comment]
1.电话号码已修改为：18030452593 。
2.钢五区的短信内容过长，请进一步详细描述。

**Comment by 1182311224** [comment]
电话号码bug已修复，测试通过。

**Comment by 1182311224** [comment]
钢五区短信内容过长问题请见附件截图
![2016-07-29 4 09 32](https://cloud.githubusercontent.com/assets/20570761/17242007/941c8512-55a7-11e6-9021-682faf60615b.png)
